### PR TITLE
Fixes gradle publishing

### PR DESCRIPTION
**Pull request by ThadHouse**
Required gradle > 3.0 to fix, and this broke the lombok plugin. Looking
online, it looked like we could just include it as a compile only
dependency. @sciencewhiz can you please check this out and make sure
everything works properly.

### CODE REVIEW

**Comment by SamCarlberg** [comment]
Yes, lombok should be a `compileOnly` dependency

**Comment by JLLeitschuh** [comment]
Does this actually work though?

**Comment by ThadHouse** [comment]
Publishing works. I have no clue what lombok does, so don't know how to test it. The program seemed to run though.

**Comment by JLLeitschuh** [comment]
Lombok dynamically rewrites the Java AST (abstract syntax tree) that the java compiler sees. I'm surprised you don't need to do custom compiler configuration to make this work.

**Comment by sciencewhiz** [comment]
I looked at the uses of lombok. In many places, behavior would change if lombok was not used, but it would still compile (ie SneakyThrows, NonNull, EqualsAndHashCode, UtilityClass)

Other places, I would expect it to not compile (ie Data, NoArgsConstructor, AllArgsConstructor, Getter, Value) although it's quite possible the code isn't taking advantage of the methods those generate and thus still could compile.

**Comment by sciencewhiz** [comment]
This fixed publishing locally, and i didn't notice any regressions. This makes #47 obe.

**Comment by JLLeitschuh** [comment]
Thanks for doing your due diligence RE lombok @sciencewhiz

**Pull request merged**
