### PR TITLE
A pull request to have a quick conversation about getting the output to result in the new Model.

### PR DESCRIPTION
**Pull request by cpapplefamily**
I don't expect this to get accepted due to it only having Java exporters. The process of getting this to this point has defiantly taught me a lot about the new Command Base Model. There are a few issues I have not addressed fully or don't have a solution for. 

One are the PID_______ options. Some of the limit Input and Outputs are now removed and need different approaches to get the original reaction to these variables. 

The other is the new command Groups and how to populate the button bindings or Smartdashboard command objects with the required subsystems that will be needed. 

Other Things yet to do but if this is not the direction of Robotbuilder in 2020 I'm not going to put much more effort into it.  *Update Help files, *export format adjustment, *add more of the new command types to name a few

### CODE REVIEW

**Comment by sciencewhiz** [comment]
Can you merge with master? @Nico1999 commits were merged in #155 and so it will be much easier to review after merge.

**Comment by cpapplefamily** [comment]
> Can you merge with master? @Nico1999 commits were merged in #155 and so it will be much easier to review after merge.

I'm not quite following your request. I'm a bit of a novice on the intricacies of git.

**Comment by sciencewhiz** [comment]
That merge looks like it worked

**Comment by sciencewhiz** [comment]
The proposed templates for VS Code may help as well https://github.com/wpilibsuite/allwpilib/pull/2016/files

**Comment by sciencewhiz** [comment]
Here's some very preliminary comments

- [ ] commands marked as autonomous selection are not added to the sendable chooser
- [ ] JoystickButtons should support WhenHeld and ToggleWhenPressed
- [ ] for a command with timeout added to smart dashboard, you can cast to Sendable so that it will compile eg `SmartDashboard.putData("CommandTimeout", (Sendable) new CommandTimeout().withTimeout(5.0));`
- [ ] Setting Run when disabled doesn't seem to change anything

**Comment by sciencewhiz** [comment]
@cpapplefamily are you going to be able to work on this any more?

**Comment by cpapplefamily** [comment]
I was on a sprint to get this far before starting my new job after the last one of 22 years moved to China. I was able to devote alot of time at work while waiting for emergencies. 
Time now is a bit more precious and I had tabled this for two reasons. 

One the above job change.

Two watching the project it appeared there where others also working on it at the same time. If this is not the case and I was the only one working on the 2020 command model Robotbuilder I could move this up on my prioritize list.

**Comment by cpapplefamily** [comment]
Also since I was only working the JAVA side I internally suspected my work was going to be used as a reference for one of the project owners might use to finish and keep both the CPP and JAVA exporters inline

**Comment by sciencewhiz** [comment]
Merged in #185

**Pull request closed without merging**
