### PR TITLE
Fix joystick construction and declaration for joysticks extensions

### PR DESCRIPTION
**Pull request by cpapplefamily**
The added Macro #type2($component) returns the type of component not the Class Name as the #type($component) seems to return. With this change I have made a extension set that adds a joystick entry for XBox Controller and XBox Buttons This address issue #32 and opens the door to create other joysticks addons.

It maybe a good Idea to change the #type($component) to something more representative of the returning a Class name if I am seeing this correctly 

As with the other edits I have summited these only focus on the Java files

I can share my Extension as well

### CODE REVIEW

**Comment by cpapplefamily** [comment]
I see this includes alot of my other changes that are under review. I may have done this incorrectly.

**Comment by sciencewhiz** [comment]
If you created the branch from your previous branch it will have all those commits. You need to create the branch from the NewCommandFramework branch to have a clean PR.

**Comment by cpapplefamily** [comment]
Ya that is basically what I did. I'm still getting a grip on the work flow. I'll clean that all up. Should I hard code my Xbox controller object into Robotbuilder-JAVA or leave it as an extension? I been thinking should we extract more of the hard-coded objects out and have the installer populate the extension folder with them. This could spark a few people to add features, and un-bind then from the base code, but it could be argued these are WPILib objects so burying them in the source is  acceptable.

**Comment by sciencewhiz** [comment]
The intent is that WPILib Objects are supported out of the box, with extensions available for third party's to add support for other features.

**Comment by cpapplefamily** [comment]
> The intent is that WPILib Objects are supported out of the box, with extensions available for third party's to add support for other features.

Ok that is what I did with the Issue #271 Pull request that I just started over to get a clean commit history.

**Pull request closed without merging**
