### PR TITLE
Fix validation of Parameters

### LINKED ISSUE #255: boolean constants fail validation

### LINKED ISSUE #277: Setpoint command Parameter Presets fails to populate with Required Subsystems Constants
The Parameter Presets for a Setpoint command does list the constants of the selected required subsystem but when chosen it does not populate the drop down selector. The selector seems to only except numbers. Not strings such as PIDSubsystem1.Up where Up is a constant of the PIDSubsystem 1.

### PR DESCRIPTION
**Pull request by sciencewhiz**
Fixes #255. Fixes #277

### CODE REVIEW

**Comment by sciencewhiz** [comment]
@cpapplefamily can you test?

**Comment by cpapplefamily** [comment]
I'll take a look Friday

**Comment by cpapplefamily** [comment]
@sciencewhiz My first look has my reported issue #277 is seemingly resolved. Not sure what the Bool Validation #255 was but I did add a Boolean constant to my project with not apparent issues. 

Three things I did observe are
One When I opened the project it warned me that it was not compatible with the current install. "Do I want to import. I said NO. build.gradle is pointing to version 2021.1.1-beta-1 and I do not have access to the beta this year. The luck of the draw was not in our favor.

Issue two is also likely related to my 2020 install of WPI_VSCode. When I ran this robotbuilder I had none of my 3rd party addons like TalonSRX's or our custom add-in we developed for our limelight enhanced TalonSRX or others.

The third is my PIDSubsystem1 is not responding to commands. Breadcrumbs in my periodic method @Override
    ```
public void periodic() {
        // This method will be called once per scheduler run
        SmartDashboard.putBoolean("Enabled", this.isEnabled());
        SmartDashboard.putNumber("SetPoint", this.getSetpoint());
        
    } 
```shows the PIDSubsystem is enabled and the Setpoint is updating but BreadCrumbs in the getMeasurement() and the useOutput(double output, double setpoint) are never getting called. I will continue to look deeper into this when more time opens up.

The PID function does seem to be unstable at the moment with Live window and Teliop not working.

**Comment by sciencewhiz** [comment]
> Three things I did observe are
> One When I opened the project it warned me that it was not compatible with the current install. "Do I want to import. I said NO. build.gradle is pointing to version 2021.1.1-beta-1 and I do not have access to the beta this year. The luck of the draw was not in our favor.

Note that if you let vscode import it, it will convert the 2021 project to 2020.
 
> Issue two is also likely related to my 2020 install of WPI_VSCode. When I ran this robotbuilder I had none of my 3rd party addons like TalonSRX's or our custom add-in we developed for our limelight enhanced TalonSRX or others.

Yes, since Robotbuilder has been updated for 2021, it will pull the extensions from the 2021 folder, rather then 2020.

> 
> The third is my PIDSubsystem1 is not responding to commands. Breadcrumbs in my periodic method @override
> ```
> public void periodic() {
> // This method will be called once per scheduler run
> SmartDashboard.putBoolean("Enabled", this.isEnabled());
> SmartDashboard.putNumber("SetPoint", this.getSetpoint());
> 
> ```
> } 
> ```

Whoops. #233 put the call to super.periodic() in Subsystem's periodic and not PIDSubsystem's periodic. It's necessary to run the PID controller.

**Comment by cpapplefamily** [comment]
@sciencewhiz is there a way to create for myself the full wpi installer to get a full experience of the beta without being in the beta group? I'm getting a hang on building the tools as push to the git repositories but having the full package would be great too.

**Comment by cpapplefamily** [comment]
@sciencewhiz let me know if things have been patched I can run the test again.

**Pull request merged**
