### PR TITLE
Add New Component type.

### PR DESCRIPTION
**Pull request by cpapplefamily**
I have been working on improving the TalonSRX and VictorSPX add-on extensions for robot builder. Also seeing more CAN enabled devices each year this could be an advantage to isolate these in the context menus when adding components to our Robotbuilder projects.  For now I have been creating a CANSpeedControllerGroup to leverage the follow features.  Jacob from CTRE said he will work on posting their extensions publicly so the community can submit Pull Request to help improve the functionality of their add-on's. Adding this type will not break the CTRE extensions in its current state only new profiles that would require PIDCANOutput devices and even then the context menues would not have any valid objects to add.. 

As a final note when things level off on development of the other tools in the suite. Maybe a file in the root of the extensions folder to parse custom types to components would be helpful.
A first look might look like this?
**ComponentTypes.yaml**
`Command: {}
Subsystem: {}
PIDOutput: {PIDCANOutput: ($quantity)}
PIDSource: {}
Sensor: {}
Controller: {}
Actuator: {}
Joystick: {}
Joystick Button: {}`

Then ($quantity) would copy the value hard coded already for the components that support the PIDOutput

### CODE REVIEW

**Comment by cpapplefamily** [comment]
An alternative to adding a way to inject custom component types would be to allow a to be multitude types. In the case of the TalonSRX is coded to be a 
`type: PIDOutput`
If `type: {PIDOutput, PIDCANOutput}` was allowed it would possibly solve the problem too.

**Comment by sciencewhiz** [comment]
What will you use PIDCANOutput for? 

This PR should be rebased on master, since it has some of the same commits as PR #120 that was merged.

**Comment by cpapplefamily** [comment]
I was working on a new SpeedControlerGroup called CANspeedControlerGroup to utilize the Follow function of CAN motor controllers. Having this type i can validate CAN motor types. One issue i did have in my branch that will need to be sorted out after getting this type is the current drivetrains exporter when i added my new group it populated with place holders. It will need to populate with the $Master-PIDCANOutput.

I started working on this and adding variables to the installed TalonSRX extension installed by CTRE adding encoder configuration and other commonly set variables. I did ask Jacob to put their extensions up on GITHUB as well to allow the community to help add functionality to the tools.  I understand why they don't put alot of resources on then but we can to help everyone.

**Comment by cpapplefamily** [comment]
As for the rebased i'm a advanced noob so i'm not clear on that process.

**Comment by sciencewhiz** [comment]
Given that use case, PIDCANOutput doesn't make sense, as there isn't a common interface that CAN Speed controllers follow. Perhaps CTRECANSpeedController, at which point it makes sense for extensions to be able to define their own types, but that's a much bigger change.

**Comment by cpapplefamily** [comment]
I graciously disagree on the use cases. With the popularity of VictorSPX, TalonSRX, Spark and DMC60C. The last two presumably having command follow. Most FRC drivetrains having multiple motors with encoders if programmers use some of the more advanced SRX features already having the slave drives configured is ideal. 

Agreeably though allowing extensions to define their own object type and injecting that into the relative subsystem, controller, oi, ect would be the most dynamic and long term fix. Hard to say if there will be many more unique cases in the future. The current id of object types is well defined. 

I suppose what I'll do when i get back to the project is create my own TalonSRX, VictorSPX, CANSpeedcontroler, and differentialDrive addons with unique validators, and exporters. Since I did identify a small issue there too. It will double theses objects in the context menu similar if your using the TalonSRX as PWM or CAN user select that unique entry.

**Comment by cpapplefamily** [comment]
Edit: I realized your not sighting use case but a lack of a common higher lever interfaces. With that your argument is more valid.

**Pull request closed without merging**
