### PR TITLE
Add frc namespace to wpilib calls

### LINKED ISSUE #55: Use frc namespace

### PR DESCRIPTION
**Pull request by sciencewhiz**
Fixes #55

### CODE REVIEW

**Comment by sciencewhiz** [comment]
@phurley @SamCarlberg do you have any C++ extensions that you can test with this? I'm afraid it might break extensions not in the frc namespace.

**Comment by SamCarlberg** [comment]
I'm only aware of CTRE's extensions

**Comment by sciencewhiz** [comment]
Yes, it broke CANTalon

**Comment by sciencewhiz** [comment]
Fixed the export of none frc namespace items and tested with CANTalon. Still potentially worried about extensions that export commands

**Comment by JLLeitschuh** [comment]
As this is an API breaking change (I know you already did it in WPI Lib, you are bumping the major version number for this year right)?

**Comment by sciencewhiz** [comment]
The RobotBuilser version is currently used to version the yaml input file. This change affects the generated code but not the input. If the RB version was bumped, older versions of RB would refuse to open yaml files created by this version, which is not correct. 

RB versioning could definitely be improved, but until it is I don’t think this PR should bump the version number.

**Comment by JLLeitschuh** [comment]
No, I'm asking if WPILib had its version number bumped.

**Comment by sciencewhiz** [comment]
WPILIB uses year based versioning. The FRC namespace change was made last year, with a shim to allow teams to continue to use old code without having to reference the FRC namespace.

**Comment by PeterJohnson** [comment]
Note CANTalon will need to be updated in a separate PR as that namespace, include files, etc, all broke.

**Pull request merged**
