### PR TITLE
[WIP] Improve encapsulation by removing RobotMap.

### PR DESCRIPTION
**Pull request by sciencewhiz**
Objects are now declared private in the Subystem.

### CODE REVIEW

**Comment by JLLeitschuh** [comment]
Is this an incompatible change making it difficult for teams to port forward their code using robot builder?

**Comment by SamCarlberg** [comment]
@JLLeitschuh RobotBuilder-generated projects will be backwards incompatible in 2019 anyway due to the move to the Gradle build system.  Why do you think teams will want to edit old programs in RobotBuilder?

**Comment by JLLeitschuh** [comment]
Just checking to make sure that this has been considered.

**Comment by bradamiller** [comment]
It has been considered. In fact removing RobotMap all together. I have a sample project for GearsBot that I wrote by hand as a model for what RobotBuilder might be able to do. I'll put it up somewhere for feedback.

**Comment by bradamiller** [comment]
That's weird, I thought I was posting into an issue. I have to try out this pull request. Thanks Joe.

**Comment by bradamiller** [comment]
I've got to go out so I'll look at your PR a little later. In the mean time, this is the GearsBot sample java program written by hand in a style that I think is pretty good. Any comments?

https://github.com/bradamiller/GearsBotByHand

**Comment by sciencewhiz** [comment]
No big rush

**Comment by bradamiller** [comment]
Generated this: 
`    protected double returnPIDInput() {
        // Return your input value for the PID loop
        // e.g. a sensor, like a potentiometer:
        // yourPot.getAverageVoltage() / kYourMaxVoltage;

        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=SOURCE
        return ${helper.getInstruction($component, "PID")};

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=SOURCE
    }
`
in a PIDSubsytem.

**Comment by bradamiller** [comment]
Looks much better than before, and not having the RobotMap isn't a problem since you can always do the HTML port map. Pretty much what I did.

**Pull request merged**
