### PR TITLE
GitHub Actions

### PR DESCRIPTION
**Pull request by AustinShalit**
Build here: https://github.com/AustinShalit/RobotBuilder/actions/runs/210002727

### CODE REVIEW

**Comment by sciencewhiz** [comment]
Can you test with #227?

**Comment by sciencewhiz** [comment]
Does this publish the test results?

**Comment by AustinShalit** [comment]
Actions does not have a test report viewer like Azure does.

**Comment by sciencewhiz** [comment]
Does it publish the results? The html and compile tests are not easily parsable on the console, but have jacoco test reports that could be downloaded.

**Comment by sciencewhiz** [comment]
Superseded by #603

**Pull request closed without merging**
